CREATE TABLE IF NOT EXISTS user_provider_config (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_scope VARCHAR(32) NOT NULL COMMENT 'llm / embedding / asr / search / oss / voiceprint',
    provider_name VARCHAR(64) DEFAULT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    base_url VARCHAR(255) DEFAULT NULL,
    model VARCHAR(128) DEFAULT NULL,
    api_key_ciphertext TEXT DEFAULT NULL,
    access_key_ciphertext TEXT DEFAULT NULL,
    secret_key_ciphertext TEXT DEFAULT NULL,
    endpoint VARCHAR(255) DEFAULT NULL,
    bucket VARCHAR(128) DEFAULT NULL,
    region_name VARCHAR(128) DEFAULT NULL,
    dimensions INT DEFAULT NULL,
    extra_config_json JSON DEFAULT NULL,
    last_check_status VARCHAR(32) DEFAULT NULL COMMENT 'unknown / ready / incomplete / invalid',
    last_check_message VARCHAR(255) DEFAULT NULL,
    last_checked_at DATETIME DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_provider_scope (user_id, provider_scope),
    KEY idx_user_provider_user_id (user_id),
    KEY idx_user_provider_scope (provider_scope)
);
