CREATE TABLE IF NOT EXISTS copilot_prep_session (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    application_id BIGINT DEFAULT NULL,
    resume_file_id BIGINT DEFAULT NULL,
    job_prep_session_id BIGINT DEFAULT NULL,
    company VARCHAR(128) DEFAULT NULL,
    job_title VARCHAR(128) DEFAULT NULL,
    jd_text TEXT DEFAULT NULL,
    notes VARCHAR(1000) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ready',
    summary VARCHAR(1000) DEFAULT NULL,
    opening_brief_json TEXT DEFAULT NULL,
    key_risks_json TEXT DEFAULT NULL,
    live_cues_json TEXT DEFAULT NULL,
    follow_up_questions_json TEXT DEFAULT NULL,
    provider_readiness_json TEXT DEFAULT NULL,
    next_actions_json TEXT DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_copilot_prep_user_update (user_id, update_time),
    KEY idx_copilot_prep_job_prep (job_prep_session_id),
    KEY idx_copilot_prep_application (application_id)
);
